POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "full_name": "bagas",
    "email": "bagas123@spendwise.com",
    "password": "bagas123"
}

###
PUT http://localhost:3000/api/auth/update-profile
Content-Type: application/json

{
  "email": "bagas123@gmail.com",
  "password": "#bagas123"
}

# cek expense
###
GET http://localhost:3000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw

# tambah expense
###
POST http://localhost:3000/api/expenses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw

{
  "category": "Ayam Goreng",
  "amount": 10000,
  "date": "2025-03-04",
  "icon": "🍗"
}

### update expense
PUT http://localhost:3000/api/expenses/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw

{
  "category": "Transport",
  "amount": 50000,
  "date": "2025-03-05",
  "icon": "🚗"
}

### hapus expense
DELETE http://localhost:3000/api/expenses/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw

# cek income
###
GET http://localhost:3000/api/income
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw

### tambah income
POST http://localhost:3000/api/income
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw

{
  "source": "Joki Web",
  "amount": 100000,
  "date": "2025-03-04",
  "icon": "💰"
}

### edit income
PUT http://localhost:3000/api/income/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw

{
  "source": "Joki Web",
  "amount": 200000,
  "date": "2025-03-05",
  "icon": "💻"
}

### hapus income
DELETE http://localhost:3000/api/income/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw


# cek balance
###
GET http://localhost:3000/api/dashboard/monthly
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw


### recent transaction
GET http://localhost:3000/api/dashboard/transactions/recent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw

### monthly
GET http://localhost:3000/api/balance/monthly-balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw

### monthly
GET http://localhost:3000/api/balance/summary-by-date
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYWdhczEyM0BzcGVuZHdpc2UuY29tIiwiaWF0IjoxNzQxNjYxODk1LCJleHAiOjE3NDE3NDgyOTV9.wKUUCMWupFpzgG0TJFTcBEnlLx632clhxJbBMQjhBaw
